version: '3.8'


volumes:
    studentsDB:

networks:
    mysqlNET:
    studentsNET:

services:
    mysql:
        image: "mysql:5.7"
        container_name: mysql
        networks:
            - mysqlNET
        ports:
            - "3306:3306"
        volumes:
            - studentsDB:/var/lib/mysql
        environment:
            - MYSQL_PASSWORD=1234
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_ROOT_HOST=%
            
    studentsapp:
        build:
            context: .
            dockerfile: StudentsDemoApp/Dockerfile
        container_name: studentsapp-api
        networks:
            - mysqlNET
            - studentsNET
        ports:
            - 5000:80
        environment:
            - DBHOST=mysql
        depends_on:
            - mysql